export const GET_CURRENT_USER_DATA = "GET_CURRENT_USER_DATA";
export const REMOVE_CURRENT_USER_DATA = "REMOVE_CURRENT_USER_DATA";

export const GET_SHOP_DATA="GET_SHOP_DATA";
export const REMOVE_SHOP_DATA="REMOVE_SHOP_DATA";
export const UPDATE_SHOP_DATA="UPDATE_SHOP_DATA";

export const GET_SERVICES_LIST = "GET_SERVICES_LIST";
export const SET_SERVICES_LIST = "SET_SERVICES_LIST";