export const GET_CURRENT_USER_DATA = "GET_CURRENT_USER_DATA";
export const REMOVE_CURRENT_USER_DATA = "REMOVE_CURRENT_USER_DATA";

export const GET_SHOP_DATA="GET_SHOP_DATA";
// shop
// hair
export const ADD_TO_HAIR ="ADD_TO_HAIR";
export const REMOVE_FROM_HAIR="REMOVE_FROM_HAIR";
// beard 
export const ADD_TO_BEARD ="ADD_TO_BEARD";
export const REMOVE_FROM_BEARD="REMOVE_FROM_BEARD";

// head massag 
export const ADD_TO_HEAD_MASSAG ="ADD_TO_HEAD_MASSAG";
export const REMOVE_FROM_HEAD_MASSAG="REMOVE_FROM_HEAD_MASSAG";

// hair color 

export const ADD_TO_HAIR_COLOR ="ADD_TO_HAIR_COLOR";
export const REMOVE_FROM_HAIR_COLOR="REMOVE_FROM_HAIR_COLOR";
export const REMOVE_SHOP_DATA="REMOVE_SHOP_DATA";
export const UPDATE_SHOP_DATA="UPDATE_SHOP_DATA";

export const GET_SERVICES_LIST = "GET_SERVICES_LIST";
export const SET_SERVICES_LIST = "SET_SERVICES_LIST";
