export const GET_CURRENT_USER_DATA = "GET_CURRENT_USER_DATA";
export const REMOVE_CURRENT_USER_DATA = "REMOVE_CURRENT_USER_DATA";

export const GET_SHOP_DATA="GET_SHOP_DATA";
export const SET_SHOP_DATA="SET_SHOP_DATA";



export const REMOVE_SHOP_DATA="REMOVE_SHOP_DATA";
export const UPDATE_SHOP_DATA="UPDATE_SHOP_DATA";

export const GET_SERVICES_LIST = "GET_SERVICES_LIST";
export const SET_SERVICES_LIST = "SET_SERVICES_LIST";


export const GET_OWNER_SHOP_DATA="GET_OWNER_SHOP_DATA";
export const SET_OWNER_SHOP_DATA="SET_OWNER_SHOP_DATA";

export const GET_ALL_SHOPS_DATA = "GET_ALL_SHOPS_DATA";
export const SET_ALL_SHOPS_DATA = "SET_ALL_SHOPS_DATA";
export const SEARCH_ALL_SHOPS_DATA = "SEARCH_ALL_SHOPS_DATA";

export const GET_OWNER_CUSTOMER_DATA="GET_OWNER_CUSTOMER_DATA";
export const SET_OWNER_CUSTOMER_DATA="SET_OWNER_CUSTOMER_DATA";

export const USER_LOCATION_POINTS = "USER_LOCATION_POINTS"

export const GET_BOOKED_SLOTS ="GET_BOOKED_SLOTS";
export const SET_BOOKED_SLOTS ="SET_BOOKED_SLOTS";
export const CLEAR_BOOKED_SLOTS= "CLEAR_BOOKED_SLOTS";
export const SERVICE_IS_CLICKED="SERVICE_IS_CLICKED";

export const CLEAR_BOOKING_DATA="CLEAR_BOOKING_DATA";

export const ADD_TIME_SLOT="ADD_TIME_SLOT";
export const UPDATE_DATE="UPDATE_DATE";

export const UPDATE_STARTING_TIME="UPDATE_STARTING_TIME";
export const UPDATE_ENDING_TIME="UPDATE_ENDING_TIME";

export const GET_MY_APPOINTMENTS = "GET_MY_APPOINTMENTS";
export const SET_MY_APPOINTMENTS = "SET_MY_APPOINTMENTS";
export const DELETE_MY_APPOINTMENTS = "DELETE_MY_APPOINTMENTS";


